apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infranew.name" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "infranew.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "infranew.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ include "infranew.name" . }}-postgres-config
            - secretRef:
                name: {{ include "infranew.name" . }}-postgres-secret
          volumeMounts:
            - name: {{ include "infranew.name" . }}-postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: {{ include "infranew.name" . }}-postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "infranew.name" . }}-postgres-pvc
