apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infranew.name" . }}-postgres-config
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: postgres
  POSTGRES_HOST: {{ include "infranew.name" . }}-postgres-service
  POSTGRES_PORT: "5432"
  COST_DB: costdb
