apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "infranew.name" . }}-postgres-migration
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate-db
          image: "{{ .Values.infranew.image.repository }}:{{ .Values.infranew.image.tag | default .Chart.AppVersion }}"
          command: ["sh", "-c", "cd apps/remix-frontend && npm run db:push"]
          env:
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          envFrom:
            - configMapRef:
                name: {{ include "infranew.name" . }}-postgres-config
            - secretRef:
                name: {{ include "infranew.name" . }}-postgres-secret
