apiVersion: v1
kind: Service
metadata:
  name: {{ include "infranew.name" . }}-postgres-service
spec:
  selector:
    app: {{ include "infranew.name" . }}-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
