name: Release Helm Charts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/1009424727351/locations/global/workloadIdentityPools/github-id-pool/providers/github-id-pool-provider"
          service_account: github-releaser@infra-new-dev.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Package Helm chart
        run: |
          helm package infra-new-chart/
          echo "CHART_PACKAGE=$(ls *.tgz)" >> $GITHUB_ENV

      - name: Upload chart to GCS bucket
        run: |
          gsutil cp *.tgz gs://infra-new-charts/
          echo "Successfully uploaded ${{ env.CHART_PACKAGE }} to gs://infra-new-charts/"

      - name: Update chart index
        run: |
          # Download existing index if it exists
          gsutil cp gs://infra-new-charts/index.yaml ./index.yaml || echo "No existing index found"

          # Generate/update the index
          helm repo index . --url https://storage.googleapis.com/infra-new-charts --merge index.yaml

          # Upload the updated index
          gsutil cp index.yaml gs://infra-new-charts/
          echo "Updated chart repository index"
